#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
apt-get update
apt-get install -y nginx

# Get the hostname of the server
hostname=$(hostname)

# Configure Nginx to add custom header
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    add_header X-Served-By $hostname;
}
EOF

# Restart Nginx
systemctl restart nginx

